# Generated by gen_vector.py

.intel_syntax noprefix
.section .text.vectors
.code64

.extern trap_enter_all

    vector_0:
    push 0
    push 0
    jmp trap_enter_all

    vector_1:
    push 0
    push 1
    jmp trap_enter_all

    vector_2:
    push 0
    push 2
    jmp trap_enter_all

    vector_3:
    push 0
    push 3
    jmp trap_enter_all

    vector_4:
    push 0
    push 4
    jmp trap_enter_all

    vector_5:
    push 0
    push 5
    jmp trap_enter_all

    vector_6:
    push 0
    push 6
    jmp trap_enter_all

    vector_7:
    push 0
    push 7
    jmp trap_enter_all

    vector_8:
    push 8
    jmp trap_enter_all

    vector_9:
    push 0
    push 9
    jmp trap_enter_all

    vector_10:
    push 10
    jmp trap_enter_all

    vector_11:
    push 11
    jmp trap_enter_all

    vector_12:
    push 12
    jmp trap_enter_all

    vector_13:
    push 13
    jmp trap_enter_all

    vector_14:
    push 14
    jmp trap_enter_all

    vector_15:
    push 0
    push 15
    jmp trap_enter_all

    vector_16:
    push 0
    push 16
    jmp trap_enter_all

    vector_17:
    push 17
    jmp trap_enter_all

    vector_18:
    push 0
    push 18
    jmp trap_enter_all

    vector_19:
    push 0
    push 19
    jmp trap_enter_all

    vector_20:
    push 0
    push 20
    jmp trap_enter_all

    vector_21:
    push 0
    push 21
    jmp trap_enter_all

    vector_22:
    push 0
    push 22
    jmp trap_enter_all

    vector_23:
    push 0
    push 23
    jmp trap_enter_all

    vector_24:
    push 0
    push 24
    jmp trap_enter_all

    vector_25:
    push 0
    push 25
    jmp trap_enter_all

    vector_26:
    push 0
    push 26
    jmp trap_enter_all

    vector_27:
    push 0
    push 27
    jmp trap_enter_all

    vector_28:
    push 0
    push 28
    jmp trap_enter_all

    vector_29:
    push 0
    push 29
    jmp trap_enter_all

    vector_30:
    push 0
    push 30
    jmp trap_enter_all

    vector_31:
    push 0
    push 31
    jmp trap_enter_all

    vector_32:
    push 0
    push 32
    jmp trap_enter_all

    vector_33:
    push 0
    push 33
    jmp trap_enter_all

    vector_34:
    push 0
    push 34
    jmp trap_enter_all

    vector_35:
    push 0
    push 35
    jmp trap_enter_all

    vector_36:
    push 0
    push 36
    jmp trap_enter_all

    vector_37:
    push 0
    push 37
    jmp trap_enter_all

    vector_38:
    push 0
    push 38
    jmp trap_enter_all

    vector_39:
    push 0
    push 39
    jmp trap_enter_all

    vector_40:
    push 0
    push 40
    jmp trap_enter_all

    vector_41:
    push 0
    push 41
    jmp trap_enter_all

    vector_42:
    push 0
    push 42
    jmp trap_enter_all

    vector_43:
    push 0
    push 43
    jmp trap_enter_all

    vector_44:
    push 0
    push 44
    jmp trap_enter_all

    vector_45:
    push 0
    push 45
    jmp trap_enter_all

    vector_46:
    push 0
    push 46
    jmp trap_enter_all

    vector_47:
    push 0
    push 47
    jmp trap_enter_all

    vector_48:
    push 0
    push 48
    jmp trap_enter_all

    vector_49:
    push 0
    push 49
    jmp trap_enter_all

    vector_50:
    push 0
    push 50
    jmp trap_enter_all

    vector_51:
    push 0
    push 51
    jmp trap_enter_all

    vector_52:
    push 0
    push 52
    jmp trap_enter_all

    vector_53:
    push 0
    push 53
    jmp trap_enter_all

    vector_54:
    push 0
    push 54
    jmp trap_enter_all

    vector_55:
    push 0
    push 55
    jmp trap_enter_all

    vector_56:
    push 0
    push 56
    jmp trap_enter_all

    vector_57:
    push 0
    push 57
    jmp trap_enter_all

    vector_58:
    push 0
    push 58
    jmp trap_enter_all

    vector_59:
    push 0
    push 59
    jmp trap_enter_all

    vector_60:
    push 0
    push 60
    jmp trap_enter_all

    vector_61:
    push 0
    push 61
    jmp trap_enter_all

    vector_62:
    push 0
    push 62
    jmp trap_enter_all

    vector_63:
    push 0
    push 63
    jmp trap_enter_all

    vector_64:
    push 0
    push 64
    jmp trap_enter_all

    vector_65:
    push 0
    push 65
    jmp trap_enter_all

    vector_66:
    push 0
    push 66
    jmp trap_enter_all

    vector_67:
    push 0
    push 67
    jmp trap_enter_all

    vector_68:
    push 0
    push 68
    jmp trap_enter_all

    vector_69:
    push 0
    push 69
    jmp trap_enter_all

    vector_70:
    push 0
    push 70
    jmp trap_enter_all

    vector_71:
    push 0
    push 71
    jmp trap_enter_all

    vector_72:
    push 0
    push 72
    jmp trap_enter_all

    vector_73:
    push 0
    push 73
    jmp trap_enter_all

    vector_74:
    push 0
    push 74
    jmp trap_enter_all

    vector_75:
    push 0
    push 75
    jmp trap_enter_all

    vector_76:
    push 0
    push 76
    jmp trap_enter_all

    vector_77:
    push 0
    push 77
    jmp trap_enter_all

    vector_78:
    push 0
    push 78
    jmp trap_enter_all

    vector_79:
    push 0
    push 79
    jmp trap_enter_all

    vector_80:
    push 0
    push 80
    jmp trap_enter_all

    vector_81:
    push 0
    push 81
    jmp trap_enter_all

    vector_82:
    push 0
    push 82
    jmp trap_enter_all

    vector_83:
    push 0
    push 83
    jmp trap_enter_all

    vector_84:
    push 0
    push 84
    jmp trap_enter_all

    vector_85:
    push 0
    push 85
    jmp trap_enter_all

    vector_86:
    push 0
    push 86
    jmp trap_enter_all

    vector_87:
    push 0
    push 87
    jmp trap_enter_all

    vector_88:
    push 0
    push 88
    jmp trap_enter_all

    vector_89:
    push 0
    push 89
    jmp trap_enter_all

    vector_90:
    push 0
    push 90
    jmp trap_enter_all

    vector_91:
    push 0
    push 91
    jmp trap_enter_all

    vector_92:
    push 0
    push 92
    jmp trap_enter_all

    vector_93:
    push 0
    push 93
    jmp trap_enter_all

    vector_94:
    push 0
    push 94
    jmp trap_enter_all

    vector_95:
    push 0
    push 95
    jmp trap_enter_all

    vector_96:
    push 0
    push 96
    jmp trap_enter_all

    vector_97:
    push 0
    push 97
    jmp trap_enter_all

    vector_98:
    push 0
    push 98
    jmp trap_enter_all

    vector_99:
    push 0
    push 99
    jmp trap_enter_all

    vector_100:
    push 0
    push 100
    jmp trap_enter_all

    vector_101:
    push 0
    push 101
    jmp trap_enter_all

    vector_102:
    push 0
    push 102
    jmp trap_enter_all

    vector_103:
    push 0
    push 103
    jmp trap_enter_all

    vector_104:
    push 0
    push 104
    jmp trap_enter_all

    vector_105:
    push 0
    push 105
    jmp trap_enter_all

    vector_106:
    push 0
    push 106
    jmp trap_enter_all

    vector_107:
    push 0
    push 107
    jmp trap_enter_all

    vector_108:
    push 0
    push 108
    jmp trap_enter_all

    vector_109:
    push 0
    push 109
    jmp trap_enter_all

    vector_110:
    push 0
    push 110
    jmp trap_enter_all

    vector_111:
    push 0
    push 111
    jmp trap_enter_all

    vector_112:
    push 0
    push 112
    jmp trap_enter_all

    vector_113:
    push 0
    push 113
    jmp trap_enter_all

    vector_114:
    push 0
    push 114
    jmp trap_enter_all

    vector_115:
    push 0
    push 115
    jmp trap_enter_all

    vector_116:
    push 0
    push 116
    jmp trap_enter_all

    vector_117:
    push 0
    push 117
    jmp trap_enter_all

    vector_118:
    push 0
    push 118
    jmp trap_enter_all

    vector_119:
    push 0
    push 119
    jmp trap_enter_all

    vector_120:
    push 0
    push 120
    jmp trap_enter_all

    vector_121:
    push 0
    push 121
    jmp trap_enter_all

    vector_122:
    push 0
    push 122
    jmp trap_enter_all

    vector_123:
    push 0
    push 123
    jmp trap_enter_all

    vector_124:
    push 0
    push 124
    jmp trap_enter_all

    vector_125:
    push 0
    push 125
    jmp trap_enter_all

    vector_126:
    push 0
    push 126
    jmp trap_enter_all

    vector_127:
    push 0
    push 127
    jmp trap_enter_all

    vector_128:
    push 0
    push 128
    jmp trap_enter_all

    vector_129:
    push 0
    push 129
    jmp trap_enter_all

    vector_130:
    push 0
    push 130
    jmp trap_enter_all

    vector_131:
    push 0
    push 131
    jmp trap_enter_all

    vector_132:
    push 0
    push 132
    jmp trap_enter_all

    vector_133:
    push 0
    push 133
    jmp trap_enter_all

    vector_134:
    push 0
    push 134
    jmp trap_enter_all

    vector_135:
    push 0
    push 135
    jmp trap_enter_all

    vector_136:
    push 0
    push 136
    jmp trap_enter_all

    vector_137:
    push 0
    push 137
    jmp trap_enter_all

    vector_138:
    push 0
    push 138
    jmp trap_enter_all

    vector_139:
    push 0
    push 139
    jmp trap_enter_all

    vector_140:
    push 0
    push 140
    jmp trap_enter_all

    vector_141:
    push 0
    push 141
    jmp trap_enter_all

    vector_142:
    push 0
    push 142
    jmp trap_enter_all

    vector_143:
    push 0
    push 143
    jmp trap_enter_all

    vector_144:
    push 0
    push 144
    jmp trap_enter_all

    vector_145:
    push 0
    push 145
    jmp trap_enter_all

    vector_146:
    push 0
    push 146
    jmp trap_enter_all

    vector_147:
    push 0
    push 147
    jmp trap_enter_all

    vector_148:
    push 0
    push 148
    jmp trap_enter_all

    vector_149:
    push 0
    push 149
    jmp trap_enter_all

    vector_150:
    push 0
    push 150
    jmp trap_enter_all

    vector_151:
    push 0
    push 151
    jmp trap_enter_all

    vector_152:
    push 0
    push 152
    jmp trap_enter_all

    vector_153:
    push 0
    push 153
    jmp trap_enter_all

    vector_154:
    push 0
    push 154
    jmp trap_enter_all

    vector_155:
    push 0
    push 155
    jmp trap_enter_all

    vector_156:
    push 0
    push 156
    jmp trap_enter_all

    vector_157:
    push 0
    push 157
    jmp trap_enter_all

    vector_158:
    push 0
    push 158
    jmp trap_enter_all

    vector_159:
    push 0
    push 159
    jmp trap_enter_all

    vector_160:
    push 0
    push 160
    jmp trap_enter_all

    vector_161:
    push 0
    push 161
    jmp trap_enter_all

    vector_162:
    push 0
    push 162
    jmp trap_enter_all

    vector_163:
    push 0
    push 163
    jmp trap_enter_all

    vector_164:
    push 0
    push 164
    jmp trap_enter_all

    vector_165:
    push 0
    push 165
    jmp trap_enter_all

    vector_166:
    push 0
    push 166
    jmp trap_enter_all

    vector_167:
    push 0
    push 167
    jmp trap_enter_all

    vector_168:
    push 0
    push 168
    jmp trap_enter_all

    vector_169:
    push 0
    push 169
    jmp trap_enter_all

    vector_170:
    push 0
    push 170
    jmp trap_enter_all

    vector_171:
    push 0
    push 171
    jmp trap_enter_all

    vector_172:
    push 0
    push 172
    jmp trap_enter_all

    vector_173:
    push 0
    push 173
    jmp trap_enter_all

    vector_174:
    push 0
    push 174
    jmp trap_enter_all

    vector_175:
    push 0
    push 175
    jmp trap_enter_all

    vector_176:
    push 0
    push 176
    jmp trap_enter_all

    vector_177:
    push 0
    push 177
    jmp trap_enter_all

    vector_178:
    push 0
    push 178
    jmp trap_enter_all

    vector_179:
    push 0
    push 179
    jmp trap_enter_all

    vector_180:
    push 0
    push 180
    jmp trap_enter_all

    vector_181:
    push 0
    push 181
    jmp trap_enter_all

    vector_182:
    push 0
    push 182
    jmp trap_enter_all

    vector_183:
    push 0
    push 183
    jmp trap_enter_all

    vector_184:
    push 0
    push 184
    jmp trap_enter_all

    vector_185:
    push 0
    push 185
    jmp trap_enter_all

    vector_186:
    push 0
    push 186
    jmp trap_enter_all

    vector_187:
    push 0
    push 187
    jmp trap_enter_all

    vector_188:
    push 0
    push 188
    jmp trap_enter_all

    vector_189:
    push 0
    push 189
    jmp trap_enter_all

    vector_190:
    push 0
    push 190
    jmp trap_enter_all

    vector_191:
    push 0
    push 191
    jmp trap_enter_all

    vector_192:
    push 0
    push 192
    jmp trap_enter_all

    vector_193:
    push 0
    push 193
    jmp trap_enter_all

    vector_194:
    push 0
    push 194
    jmp trap_enter_all

    vector_195:
    push 0
    push 195
    jmp trap_enter_all

    vector_196:
    push 0
    push 196
    jmp trap_enter_all

    vector_197:
    push 0
    push 197
    jmp trap_enter_all

    vector_198:
    push 0
    push 198
    jmp trap_enter_all

    vector_199:
    push 0
    push 199
    jmp trap_enter_all

    vector_200:
    push 0
    push 200
    jmp trap_enter_all

    vector_201:
    push 0
    push 201
    jmp trap_enter_all

    vector_202:
    push 0
    push 202
    jmp trap_enter_all

    vector_203:
    push 0
    push 203
    jmp trap_enter_all

    vector_204:
    push 0
    push 204
    jmp trap_enter_all

    vector_205:
    push 0
    push 205
    jmp trap_enter_all

    vector_206:
    push 0
    push 206
    jmp trap_enter_all

    vector_207:
    push 0
    push 207
    jmp trap_enter_all

    vector_208:
    push 0
    push 208
    jmp trap_enter_all

    vector_209:
    push 0
    push 209
    jmp trap_enter_all

    vector_210:
    push 0
    push 210
    jmp trap_enter_all

    vector_211:
    push 0
    push 211
    jmp trap_enter_all

    vector_212:
    push 0
    push 212
    jmp trap_enter_all

    vector_213:
    push 0
    push 213
    jmp trap_enter_all

    vector_214:
    push 0
    push 214
    jmp trap_enter_all

    vector_215:
    push 0
    push 215
    jmp trap_enter_all

    vector_216:
    push 0
    push 216
    jmp trap_enter_all

    vector_217:
    push 0
    push 217
    jmp trap_enter_all

    vector_218:
    push 0
    push 218
    jmp trap_enter_all

    vector_219:
    push 0
    push 219
    jmp trap_enter_all

    vector_220:
    push 0
    push 220
    jmp trap_enter_all

    vector_221:
    push 0
    push 221
    jmp trap_enter_all

    vector_222:
    push 0
    push 222
    jmp trap_enter_all

    vector_223:
    push 0
    push 223
    jmp trap_enter_all

    vector_224:
    push 0
    push 224
    jmp trap_enter_all

    vector_225:
    push 0
    push 225
    jmp trap_enter_all

    vector_226:
    push 0
    push 226
    jmp trap_enter_all

    vector_227:
    push 0
    push 227
    jmp trap_enter_all

    vector_228:
    push 0
    push 228
    jmp trap_enter_all

    vector_229:
    push 0
    push 229
    jmp trap_enter_all

    vector_230:
    push 0
    push 230
    jmp trap_enter_all

    vector_231:
    push 0
    push 231
    jmp trap_enter_all

    vector_232:
    push 0
    push 232
    jmp trap_enter_all

    vector_233:
    push 0
    push 233
    jmp trap_enter_all

    vector_234:
    push 0
    push 234
    jmp trap_enter_all

    vector_235:
    push 0
    push 235
    jmp trap_enter_all

    vector_236:
    push 0
    push 236
    jmp trap_enter_all

    vector_237:
    push 0
    push 237
    jmp trap_enter_all

    vector_238:
    push 0
    push 238
    jmp trap_enter_all

    vector_239:
    push 0
    push 239
    jmp trap_enter_all

    vector_240:
    push 0
    push 240
    jmp trap_enter_all

    vector_241:
    push 0
    push 241
    jmp trap_enter_all

    vector_242:
    push 0
    push 242
    jmp trap_enter_all

    vector_243:
    push 0
    push 243
    jmp trap_enter_all

    vector_244:
    push 0
    push 244
    jmp trap_enter_all

    vector_245:
    push 0
    push 245
    jmp trap_enter_all

    vector_246:
    push 0
    push 246
    jmp trap_enter_all

    vector_247:
    push 0
    push 247
    jmp trap_enter_all

    vector_248:
    push 0
    push 248
    jmp trap_enter_all

    vector_249:
    push 0
    push 249
    jmp trap_enter_all

    vector_250:
    push 0
    push 250
    jmp trap_enter_all

    vector_251:
    push 0
    push 251
    jmp trap_enter_all

    vector_252:
    push 0
    push 252
    jmp trap_enter_all

    vector_253:
    push 0
    push 253
    jmp trap_enter_all

    vector_254:
    push 0
    push 254
    jmp trap_enter_all

    vector_255:
    push 0
    push 255
    jmp trap_enter_all

# Vector Pointer Table
.section .rodata.vectors
.align 8

.globl vectors
vectors:

    .quad vector_0
    .quad vector_1
    .quad vector_2
    .quad vector_3
    .quad vector_4
    .quad vector_5
    .quad vector_6
    .quad vector_7
    .quad vector_8
    .quad vector_9
    .quad vector_10
    .quad vector_11
    .quad vector_12
    .quad vector_13
    .quad vector_14
    .quad vector_15
    .quad vector_16
    .quad vector_17
    .quad vector_18
    .quad vector_19
    .quad vector_20
    .quad vector_21
    .quad vector_22
    .quad vector_23
    .quad vector_24
    .quad vector_25
    .quad vector_26
    .quad vector_27
    .quad vector_28
    .quad vector_29
    .quad vector_30
    .quad vector_31
    .quad vector_32
    .quad vector_33
    .quad vector_34
    .quad vector_35
    .quad vector_36
    .quad vector_37
    .quad vector_38
    .quad vector_39
    .quad vector_40
    .quad vector_41
    .quad vector_42
    .quad vector_43
    .quad vector_44
    .quad vector_45
    .quad vector_46
    .quad vector_47
    .quad vector_48
    .quad vector_49
    .quad vector_50
    .quad vector_51
    .quad vector_52
    .quad vector_53
    .quad vector_54
    .quad vector_55
    .quad vector_56
    .quad vector_57
    .quad vector_58
    .quad vector_59
    .quad vector_60
    .quad vector_61
    .quad vector_62
    .quad vector_63
    .quad vector_64
    .quad vector_65
    .quad vector_66
    .quad vector_67
    .quad vector_68
    .quad vector_69
    .quad vector_70
    .quad vector_71
    .quad vector_72
    .quad vector_73
    .quad vector_74
    .quad vector_75
    .quad vector_76
    .quad vector_77
    .quad vector_78
    .quad vector_79
    .quad vector_80
    .quad vector_81
    .quad vector_82
    .quad vector_83
    .quad vector_84
    .quad vector_85
    .quad vector_86
    .quad vector_87
    .quad vector_88
    .quad vector_89
    .quad vector_90
    .quad vector_91
    .quad vector_92
    .quad vector_93
    .quad vector_94
    .quad vector_95
    .quad vector_96
    .quad vector_97
    .quad vector_98
    .quad vector_99
    .quad vector_100
    .quad vector_101
    .quad vector_102
    .quad vector_103
    .quad vector_104
    .quad vector_105
    .quad vector_106
    .quad vector_107
    .quad vector_108
    .quad vector_109
    .quad vector_110
    .quad vector_111
    .quad vector_112
    .quad vector_113
    .quad vector_114
    .quad vector_115
    .quad vector_116
    .quad vector_117
    .quad vector_118
    .quad vector_119
    .quad vector_120
    .quad vector_121
    .quad vector_122
    .quad vector_123
    .quad vector_124
    .quad vector_125
    .quad vector_126
    .quad vector_127
    .quad vector_128
    .quad vector_129
    .quad vector_130
    .quad vector_131
    .quad vector_132
    .quad vector_133
    .quad vector_134
    .quad vector_135
    .quad vector_136
    .quad vector_137
    .quad vector_138
    .quad vector_139
    .quad vector_140
    .quad vector_141
    .quad vector_142
    .quad vector_143
    .quad vector_144
    .quad vector_145
    .quad vector_146
    .quad vector_147
    .quad vector_148
    .quad vector_149
    .quad vector_150
    .quad vector_151
    .quad vector_152
    .quad vector_153
    .quad vector_154
    .quad vector_155
    .quad vector_156
    .quad vector_157
    .quad vector_158
    .quad vector_159
    .quad vector_160
    .quad vector_161
    .quad vector_162
    .quad vector_163
    .quad vector_164
    .quad vector_165
    .quad vector_166
    .quad vector_167
    .quad vector_168
    .quad vector_169
    .quad vector_170
    .quad vector_171
    .quad vector_172
    .quad vector_173
    .quad vector_174
    .quad vector_175
    .quad vector_176
    .quad vector_177
    .quad vector_178
    .quad vector_179
    .quad vector_180
    .quad vector_181
    .quad vector_182
    .quad vector_183
    .quad vector_184
    .quad vector_185
    .quad vector_186
    .quad vector_187
    .quad vector_188
    .quad vector_189
    .quad vector_190
    .quad vector_191
    .quad vector_192
    .quad vector_193
    .quad vector_194
    .quad vector_195
    .quad vector_196
    .quad vector_197
    .quad vector_198
    .quad vector_199
    .quad vector_200
    .quad vector_201
    .quad vector_202
    .quad vector_203
    .quad vector_204
    .quad vector_205
    .quad vector_206
    .quad vector_207
    .quad vector_208
    .quad vector_209
    .quad vector_210
    .quad vector_211
    .quad vector_212
    .quad vector_213
    .quad vector_214
    .quad vector_215
    .quad vector_216
    .quad vector_217
    .quad vector_218
    .quad vector_219
    .quad vector_220
    .quad vector_221
    .quad vector_222
    .quad vector_223
    .quad vector_224
    .quad vector_225
    .quad vector_226
    .quad vector_227
    .quad vector_228
    .quad vector_229
    .quad vector_230
    .quad vector_231
    .quad vector_232
    .quad vector_233
    .quad vector_234
    .quad vector_235
    .quad vector_236
    .quad vector_237
    .quad vector_238
    .quad vector_239
    .quad vector_240
    .quad vector_241
    .quad vector_242
    .quad vector_243
    .quad vector_244
    .quad vector_245
    .quad vector_246
    .quad vector_247
    .quad vector_248
    .quad vector_249
    .quad vector_250
    .quad vector_251
    .quad vector_252
    .quad vector_253
    .quad vector_254
    .quad vector_255
