if (NOT DEFINED GNU_TOOLCHAIN_PATH)
  set(GNU_TOOLCHAIN_PATH "/usr/bin")
endif()

if (NOT DEFINED GNU_TOOLCHAIN_TARGET)
  set(GNU_TOOLCHAIN_TARGET "x86_64-pc-elf")
endif()

message("GNU Toolchain configured with ${GNU_TOOLCHAIN_PATH}/${GNU_TOOLCHAIN_TARGET}-")

set(CMAKE_AR                    "${GNU_TOOLCHAIN_PATH}/${GNU_TOOLCHAIN_TARGET}-ar")
set(CMAKE_ASM_COMPILER          "${GNU_TOOLCHAIN_PATH}/${GNU_TOOLCHAIN_TARGET}-gcc")
set(CMAKE_C_COMPILER            "${GNU_TOOLCHAIN_PATH}/${GNU_TOOLCHAIN_TARGET}-gcc")
set(CMAKE_CXX_COMPILER          "${GNU_TOOLCHAIN_PATH}/${GNU_TOOLCHAIN_TARGET}-g++")
set(CMAKE_LINKER                "${GNU_TOOLCHAIN_PATH}/${GNU_TOOLCHAIN_TARGET}-ld")
set(CMAKE_OBJCOPY               "${GNU_TOOLCHAIN_PATH}/${GNU_TOOLCHAIN_TARGET}-objcopy")
set(CMAKE_RANLIB                "${GNU_TOOLCHAIN_PATH}/${GNU_TOOLCHAIN_TARGET}-ranlib")
set(CMAKE_SIZE                  "${GNU_TOOLCHAIN_PATH}/${GNU_TOOLCHAIN_TARGET}-size")
set(CMAKE_STRIP                 "${GNU_TOOLCHAIN_PATH}/${GNU_TOOLCHAIN_TARGET}-strip")
set(CMAKE_OBJDUMP               "${GNU_TOOLCHAIN_PATH}/${GNU_TOOLCHAIN_TARGET}-objdump")

set(CMAKE_SYSTEM_NAME           Generic)
set(CMAKE_SYSTEM_PROCESSOR      x86_64)

set(CMAKE_C_COMPILER_WORKS 1)